### ISSUE TITLE
希望能开放Kage引擎修改代码

### ISSUE THREAD

**Issue by NightFurySL2001** [takushun-wu/SuperHan#1]
如上，开放修改代码可以更容易了解生成过程。

**Comment by takushun-wu** [comment]
生成字形所用到的Kage引擎是基于下面链接所提到的引擎，基本没做修改（除了能在本地nodejs上批量生成外）：
https://github.com/ge9/kage-engine-2/
文中所提到的“修改”是相对于[原始版本的Kage引擎](https://github.com/kamichikoichi/kage-engine)而言的。
